export const cuisinesSeed = [
  { name: 'Итальянская',    slug: 'italian',       icon: '🍝' },
  { name: 'Японская',       slug: 'japanese',      icon: '🍣' },
  { name: 'Грузинская',     slug: 'georgian',      icon: '🥘' },
  { name: 'Французская',    slug: 'french',        icon: '🥐' },
  { name: 'Русская',        slug: 'russian',       icon: '🥙' },
  { name: 'Паназиатская',   slug: 'pan-asian',     icon: '🍜' },
  { name: 'Китайская',      slug: 'chinese',       icon: '🥡' },
  { name: 'Узбекская',      slug: 'uzbek',         icon: '🍲' },
  { name: 'Мексиканская',   slug: 'mexican',       icon: '🌮' },
  { name: 'Индийская',      slug: 'indian',        icon: '🍛' },
  { name: 'Средиземноморская', slug: 'mediterranean', icon: '🫒' },
  { name: 'Американская',   slug: 'american',      icon: '🍔' },
  { name: 'Стейкхаус',      slug: 'steakhouse',    icon: '🥩' },
  { name: 'Морепродукты',   slug: 'seafood',       icon: '🦞' },
  { name: 'Вегетарианская', slug: 'vegetarian',    icon: '🥗' },
  { name: 'Турецкая',       slug: 'turkish',       icon: '🧆' },
  { name: 'Кавказская',     slug: 'caucasian',     icon: '🍖' },
  { name: 'Европейская',    slug: 'european',      icon: '🍽️' },
  { name: 'Авторская',      slug: 'author',        icon: '👨‍🍳' },
  { name: 'Фьюжн',          slug: 'fusion',        icon: '✨' },
];
