export interface RestaurantSeed {
  name: string;
  slug: string;
  description: string;
  citySlug: string;
  cuisineSlugs: string[];
  address: string;
  metroStation?: string;
  phone: string;
  priceLevel: number;
  averageBill: number;
  rating: number;
  reviewCount: number;
  hasWifi: boolean;
  hasDelivery: boolean;
}

export const restaurantsSeed: RestaurantSeed[] = [
  // ─── Москва ────────────────────────────────────────────
  {
    name: 'White Rabbit',
    slug: 'white-rabbit',
    description: 'Панорамный ресторан на 16 этаже Смоленского пассажа с авторской кухней шефа Владимира Мухина. Входит в рейтинг The World\'s 50 Best Restaurants.',
    citySlug: 'moscow',
    cuisineSlugs: ['author', 'european'],
    address: 'Смоленская площадь, 3',
    metroStation: 'Смоленская',
    phone: '+7 (495) 510-77-13',
    priceLevel: 4,
    averageBill: 5000,
    rating: 4.9,
    reviewCount: 324,
    hasWifi: true,
    hasDelivery: false,
  },
  {
    name: 'Сахалин',
    slug: 'sakhalin',
    description: 'Рыбный ресторан с собственным аквариумом и ежедневными поставками морепродуктов с Дальнего Востока. Устричный бар и суши-бар.',
    citySlug: 'moscow',
    cuisineSlugs: ['seafood', 'japanese'],
    address: 'Большой Козихинский пер., 13',
    metroStation: 'Пушкинская',
    phone: '+7 (495) 120-12-12',
    priceLevel: 4,
    averageBill: 4500,
    rating: 4.8,
    reviewCount: 218,
    hasWifi: true,
    hasDelivery: true,
  },
  {
    name: 'Кафе Пушкинъ',
    slug: 'cafe-pushkin',
    description: 'Легендарное заведение на Тверском бульваре, воссоздающее атмосферу дворянской России. Русская кухня в исполнении шеф-повара Андрея Махова.',
    citySlug: 'moscow',
    cuisineSlugs: ['russian', 'european'],
    address: 'Тверской бульвар, 26А',
    metroStation: 'Пушкинская',
    phone: '+7 (495) 739-00-33',
    priceLevel: 4,
    averageBill: 4000,
    rating: 4.7,
    reviewCount: 567,
    hasWifi: true,
    hasDelivery: true,
  },
  {
    name: 'Чайхона №1',
    slug: 'chayhona-1-moscow',
    description: 'Уютный ресторан узбекской и паназиатской кухни с богатым меню и аутентичной атмосферой. Хиты — плов, лагман, самса.',
    citySlug: 'moscow',
    cuisineSlugs: ['uzbek', 'pan-asian'],
    address: 'ул. Тимура Фрунзе, 11',
    metroStation: 'Парк культуры',
    phone: '+7 (495) 287-90-01',
    priceLevel: 2,
    averageBill: 1800,
    rating: 4.5,
    reviewCount: 892,
    hasWifi: true,
    hasDelivery: true,
  },
  {
    name: 'Техникум',
    slug: 'tekhnikum-moscow',
    description: 'Гастрономический бар в центре Москвы. Авторские коктейли, хосперное мясо и непринуждённая атмосфера лофта.',
    citySlug: 'moscow',
    cuisineSlugs: ['author', 'steakhouse'],
    address: 'Рождественка, 5/7с1',
    metroStation: 'Кузнецкий Мост',
    phone: '+7 (495) 775-88-90',
    priceLevel: 3,
    averageBill: 2500,
    rating: 4.6,
    reviewCount: 345,
    hasWifi: true,
    hasDelivery: false,
  },

  // ─── Санкт-Петербург ───────────────────────────────────
  {
    name: 'Birch',
    slug: 'birch-spb',
    description: 'Новая северная кухня в историческом особняке. Ферментация, дикоросы и локальные продукты. Один из лучших ресторанов Петербурга.',
    citySlug: 'spb',
    cuisineSlugs: ['author', 'russian'],
    address: 'наб. реки Мойки, 16',
    metroStation: 'Адмиралтейская',
    phone: '+7 (812) 912-12-12',
    priceLevel: 4,
    averageBill: 4000,
    rating: 4.8,
    reviewCount: 189,
    hasWifi: true,
    hasDelivery: false,
  },
  {
    name: 'EM Restaurant',
    slug: 'em-restaurant-spb',
    description: 'Ресторан грузинской кухни с панорамным видом на Казанский собор. Хинкали ручной лепки, хачапури и натуральное вино.',
    citySlug: 'spb',
    cuisineSlugs: ['georgian'],
    address: 'наб. канала Грибоедова, 5',
    metroStation: 'Невский проспект',
    phone: '+7 (812) 640-55-55',
    priceLevel: 3,
    averageBill: 2500,
    rating: 4.7,
    reviewCount: 421,
    hasWifi: true,
    hasDelivery: true,
  },
  {
    name: 'Мансарда',
    slug: 'mansarda-spb',
    description: 'Ресторан с панорамным видом на Исаакиевский собор. Итальянская и средиземноморская кухня. Одна из лучших террас города.',
    citySlug: 'spb',
    cuisineSlugs: ['italian', 'mediterranean'],
    address: 'Почтамтская ул., 3',
    metroStation: 'Адмиралтейская',
    phone: '+7 (812) 640-15-15',
    priceLevel: 3,
    averageBill: 3000,
    rating: 4.6,
    reviewCount: 512,
    hasWifi: true,
    hasDelivery: false,
  },

  // ─── Казань ────────────────────────────────────────────
  {
    name: 'Чирэм',
    slug: 'chirem-kazan',
    description: 'Ресторан татарской кухни в современном прочтении. Эчпочмак, казылык, талкыш калеве — классика в авторской подаче.',
    citySlug: 'kazan',
    cuisineSlugs: ['russian', 'author'],
    address: 'ул. Баумана, 68',
    phone: '+7 (843) 200-10-10',
    priceLevel: 3,
    averageBill: 2000,
    rating: 4.7,
    reviewCount: 276,
    hasWifi: true,
    hasDelivery: true,
  },
  {
    name: 'Pashmir',
    slug: 'pashmir-kazan',
    description: 'Индийский ресторан в центре Казани. Тандурная печь, карри с нуля, масала-чай. Вегетарианское и безглютеновое меню.',
    citySlug: 'kazan',
    cuisineSlugs: ['indian'],
    address: 'ул. Кремлёвская, 25А',
    phone: '+7 (843) 240-55-55',
    priceLevel: 2,
    averageBill: 1500,
    rating: 4.5,
    reviewCount: 198,
    hasWifi: true,
    hasDelivery: true,
  },

  // ─── Екатеринбург ──────────────────────────────────────
  {
    name: 'Гастроли',
    slug: 'gastroli-ekb',
    description: 'Винный бар и ресторан с европейской кухней. Открытая кухня, авторские десерты и карта вин на 300+ позиций.',
    citySlug: 'ekb',
    cuisineSlugs: ['european', 'french'],
    address: 'ул. 8 Марта, 8Б',
    phone: '+7 (343) 310-30-30',
    priceLevel: 3,
    averageBill: 2500,
    rating: 4.7,
    reviewCount: 234,
    hasWifi: true,
    hasDelivery: false,
  },
  {
    name: 'Мамин-Сибиряк',
    slug: 'mamin-sibiryak-ekb',
    description: 'Уральская кухня из локальных продуктов. Пельмени с олениной, муксун, уральские ягоды. Интерьер в стиле уральского модерна.',
    citySlug: 'ekb',
    cuisineSlugs: ['russian', 'author'],
    address: 'ул. Мамина-Сибиряка, 193',
    phone: '+7 (343) 287-70-70',
    priceLevel: 3,
    averageBill: 2200,
    rating: 4.6,
    reviewCount: 312,
    hasWifi: true,
    hasDelivery: true,
  },

  // ─── Новосибирск ───────────────────────────────────────
  {
    name: '#СибирьСибирь',
    slug: 'sibir-sibir-nsk',
    description: 'Сибирская кухня в центре Новосибирска. Строганина, дичь, ягоды, кедровые орехи. Современная подача региональных рецептов.',
    citySlug: 'novosibirsk',
    cuisineSlugs: ['russian', 'author'],
    address: 'ул. Ленина, 21',
    phone: '+7 (383) 200-50-50',
    priceLevel: 3,
    averageBill: 2000,
    rating: 4.6,
    reviewCount: 187,
    hasWifi: true,
    hasDelivery: false,
  },
  {
    name: 'Якитория',
    slug: 'yakitoriya-nsk',
    description: 'Ресторан японской и паназиатской кухни. Суши, роллы, вок, рамен. Доставка по всему городу.',
    citySlug: 'novosibirsk',
    cuisineSlugs: ['japanese', 'pan-asian'],
    address: 'Красный проспект, 73',
    phone: '+7 (383) 255-55-55',
    priceLevel: 2,
    averageBill: 1500,
    rating: 4.3,
    reviewCount: 654,
    hasWifi: true,
    hasDelivery: true,
  },

  // ─── Сочи ─────────────────────────────────────────────
  {
    name: 'Sea Breeze',
    slug: 'sea-breeze-sochi',
    description: 'Средиземноморский ресторан на первой линии. Свежие морепродукты, паста, вино. Открытая терраса с видом на море.',
    citySlug: 'sochi',
    cuisineSlugs: ['mediterranean', 'seafood'],
    address: 'Приморская набережная, 3',
    phone: '+7 (862) 260-30-30',
    priceLevel: 3,
    averageBill: 3000,
    rating: 4.8,
    reviewCount: 145,
    hasWifi: true,
    hasDelivery: false,
  },
  {
    name: 'Хинкальная на горе',
    slug: 'hinkalnaya-sochi',
    description: 'Грузинская кухня на горе Ахун. Хинкали, хачапури, шашлык на углях. Захватывающий вид на горы и море.',
    citySlug: 'sochi',
    cuisineSlugs: ['georgian', 'caucasian'],
    address: 'гора Ахун, 1',
    phone: '+7 (862) 254-10-10',
    priceLevel: 2,
    averageBill: 1800,
    rating: 4.5,
    reviewCount: 387,
    hasWifi: false,
    hasDelivery: false,
  },

  // ─── Краснодар ─────────────────────────────────────────
  {
    name: 'Баран-Рапан',
    slug: 'baran-rapan-krasnodar',
    description: 'Ресторан южной кухни. Местные фермерские продукты, кубанские вина, мясо на углях. Гастрономическая визитная карточка Краснодара.',
    citySlug: 'krasnodar',
    cuisineSlugs: ['russian', 'caucasian'],
    address: 'ул. Красная, 176',
    phone: '+7 (861) 200-33-33',
    priceLevel: 3,
    averageBill: 2200,
    rating: 4.7,
    reviewCount: 298,
    hasWifi: true,
    hasDelivery: true,
  },

  // ─── Нижний Новгород ──────────────────────────────────
  {
    name: 'Строганов Бар и Гриль',
    slug: 'stroganov-nnov',
    description: 'Стейк-хаус с мясом собственного вызревания. Гриль на углях, бургеры, крафтовое пиво. Вид на Волгу с летней веранды.',
    citySlug: 'nnov',
    cuisineSlugs: ['steakhouse', 'american'],
    address: 'ул. Рождественская, 45',
    phone: '+7 (831) 433-10-10',
    priceLevel: 3,
    averageBill: 2300,
    rating: 4.6,
    reviewCount: 267,
    hasWifi: true,
    hasDelivery: true,
  },

  // ─── Самара ────────────────────────────────────────────
  {
    name: 'Vinoteka',
    slug: 'vinoteka-samara',
    description: 'Винный ресторан с французской и итальянской кухней. Более 500 позиций в винной карте, сырная комната, дегустации.',
    citySlug: 'samara',
    cuisineSlugs: ['french', 'italian'],
    address: 'Ленинградская ул., 37',
    phone: '+7 (846) 270-22-22',
    priceLevel: 3,
    averageBill: 2500,
    rating: 4.5,
    reviewCount: 178,
    hasWifi: true,
    hasDelivery: false,
  },

  // ─── Уфа ──────────────────────────────────────────────
  {
    name: 'Азык Тулек',
    slug: 'azyk-tulek-ufa',
    description: 'Ресторан башкирской кухни. Бешбармак, конская колбаса, баурсак, кумыс. Этнический интерьер и живая музыка по вечерам.',
    citySlug: 'ufa',
    cuisineSlugs: ['russian', 'turkish'],
    address: 'ул. Ленина, 10',
    phone: '+7 (347) 291-10-10',
    priceLevel: 2,
    averageBill: 1500,
    rating: 4.4,
    reviewCount: 213,
    hasWifi: true,
    hasDelivery: true,
  },
];
